version: "3.3"
services:
  apacheWEB: # Servidor
    container_name: apacheWEB
    image: httpd
    ports:
      - 81:80
  kasmweb: # Cliente
    container_name: kasmweb
    image: kasmweb/desktop:1.7.0
    stdin_open: true  # docker run -i
    tty: true         # docker run -t
    dns:
      - 10.1.0.254  # el contenedor DNS server
